### ISSUE TITLE
Add switch component

### ISSUE THREAD

**Issue by cobraz** [tabetalt/kit#10]
<img width="112" alt="Skjermbilde 2020-07-11 kl  13 59 46" src="https://user-images.githubusercontent.com/3726815/87223627-d2e8f700-c37e-11ea-857c-07054bd9d42a.png">

**Comment by cobraz** [comment]
I think we should wait until system-ui/theme-ui#1035 are merged.

**Comment by cobraz** [comment]
cc: @AnneMatilde

**Comment by cobraz** [comment]
@AnneMatilde @AnneMatilde @AnneMatilde ?

**Comment by AnneMatilde** [comment]
@cobraz ?

**Comment by cobraz** [comment]
@TanyaDolgopolova Maybe you can help get system-ui/theme-ui#1035 merged?

**Comment by TanyaDolgopolova** [comment]
@cobraz I am not sure about that. What do you mean?

**Comment by cobraz** [comment]
I think, since the PR (system-ui/theme-ui#1035) has stalled for a while. Let's just (for now) copy what has been added over to tabetalt/kit.

**Comment by TanyaDolgopolova** [comment]
Okay
