### ISSUE TITLE
Add tabetalt logo

### ISSUE THREAD

**Issue by cobraz** [tabetalt/kit#13]
Implementation of the Tabetalt logo. We should have it available in the kit, so it can be easily utilized in applications.

<img width="767" alt="Skjermbilde 2020-07-11 kl  15 21 11" src="https://user-images.githubusercontent.com/3726815/87225025-2876d100-c38a-11ea-9592-57ee849031ac.png">

- [x] Export SVG
- [x] Replace color with `currentColor`
- [x] [SVGOMG](https://jakearchibald.github.io/svgomg/) optimize

We should make it super convenient to change the color for the logo. Unsure if it should be a `sx` prop, ordinary prop or just theme-based (and adjustable with `sx`).

**Comment by cobraz** [comment]
@AnneMatilde Can you provide the logo?

**Comment by AnneMatilde** [comment]
[Tabetalt_Logo.zip](https://github.com/tabetalt/kit/files/4907579/Tabetalt_Logo.zip)
