### ISSUE TITLE
Add dots icon

### ISSUE THREAD

**Issue by cobraz** [tabetalt/kit#26]
We are missing _dots icon_ in our package.

References:

![Skjermbilde 2020-09-09 kl  15 05 21](https://user-images.githubusercontent.com/3726815/92602060-eb598d00-f2ad-11ea-956c-5e69b8a7c81f.png)

![image](https://user-images.githubusercontent.com/3726815/92602004-d5e46300-f2ad-11ea-8e5f-9e44ddafe8c8.png)

**Comment by AnneMatilde** [comment]
Dots icon is now uploaded to the icon-folder on Tabetalt shared disk.
