### ISSUE TITLE
Align headings with actual styling

### ISSUE THREAD

**Issue by cobraz** [tabetalt/kit#30]
Right now, we only have a size array for headings. And it's not aligned with anything in the design.

I ask my self, is this `<h2 />`?
![Skjermbilde 2020-09-09 kl  16 52 30](https://user-images.githubusercontent.com/3726815/92614912-dafcde80-f2bc-11ea-8491-1612e01428be.png)

I wasn't able to check the design system XD files right now, due to old version of Adobe XD locally. Can you (@AnneMatilde) check if we have defined some standardized sizes?

**Comment by AnneMatilde** [comment]
I have now changed the name of the font-styles in the Adobe XD document. All text in the document is aligned with the styles.

**Comment by cobraz** [comment]
Thank you!
