### ISSUE TITLE
Adding Button Loading Variant

### ISSUE THREAD

**Issue by AnneMatilde** [tabetalt/kit#31]
I have made a new design for button loading available in the shared Adobe XD document. 
![image](https://user-images.githubusercontent.com/54155334/92965831-c82e0980-f476-11ea-9489-04e66de1cee2.png)

**Comment by cobraz** [comment]
@AnneMatilde We need these icons too! :)

**Comment by AnneMatilde** [comment]
Do we tho? @cobraz

**Comment by AnneMatilde** [comment]
Checkmark is found here: https://drive.google.com/file/d/1Hu01ClC3xCCo_bzm_PfcOxADtd5b62j8/view?usp=sharing
Spinner is found here: https://drive.google.com/file/d/1LV5bmvMGlVQorX8msPb5Sg4FJ691D_C8/view?usp=sharing
