### ISSUE TITLE
Add icons

### ISSUE THREAD

**Issue by cobraz** [tabetalt/kit#4]
Icons need to be added to the kit.

<img width="769" alt="Skjermbilde 2020-07-11 kl  13 54 13" src="https://user-images.githubusercontent.com/3726815/87223522-04ad8e00-c37e-11ea-989c-b89da7102ed9.png">

@AnneMatilde can you upload SVGs? As mentioned, we need them in one size (ex. 64x64) with the primary color replaced with `currentColor`. More about that [here](https://css-tricks.com/currentcolor/)

- [x] Export SVG icons
- [x] Replace color with `currentColor`
- [x] [SVGOMG](https://jakearchibald.github.io/svgomg/) optimize

**Comment by AnneMatilde** [comment]
[Tabetalt_icons.zip](https://github.com/tabetalt/kit/files/4906848/Tabetalt_icons.zip)
