### ISSUE TITLE
Select issue when using `<Field/>`

### ISSUE THREAD

**Issue by cobraz** [tabetalt/kit#40]
<img width="1010" alt="Skjermbilde 2020-09-19 kl  22 56 58" src="https://user-images.githubusercontent.com/3726815/93689086-72d3a700-facb-11ea-9533-2d973e087d88.png">

👆 Obvious issue above.

Repro:

```jsx
<Field label="Språk" name="lang" as={Select}>
	<option>Hello</option>
</Field>
```

**Comment by cobraz** [comment]
This is not just when using `as={Select}`, but with other non-`<Input/>` components.

![Skjermbilde 2020-09-21 kl  09 43 38](https://user-images.githubusercontent.com/3726815/93742730-ef12db00-fbee-11ea-9f05-6afc4d57673c.png)
![Skjermbilde 2020-09-21 kl  09 43 57](https://user-images.githubusercontent.com/3726815/93742750-fa660680-fbee-11ea-93ab-d9263b5b7b61.png)

**Comment by TanyaDolgopolova** [comment]
@cobraz I see that this issue assigned to you. Do I need to do this task?

**Comment by cobraz** [comment]
I don't know why I have assigned this to myself. Please go ahead :D

**Comment by TanyaDolgopolova** [comment]
Hi, I have already added new LabeledSelect component with fixing this issue PR #79 . May it can be closed?
