### ISSUE TITLE
Background is not white

### ISSUE THREAD

**Issue by cobraz** [tabetalt/kit#44]
So, in the design files, the background is `#FFFFFF` (white), but in the design system we have a color called `background` which is `#f6f6f9`. Which is correct, @AnneMatilde ?

**Comment by cobraz** [comment]
@AnneMatilde Where are you?

**Comment by AnneMatilde** [comment]
Background is white. Color with name "Background" is the lightest color of "Grey". My bad! @cobraz

**Comment by TanyaDolgopolova** [comment]
This issue already resolved?
