### ISSUE TITLE
(Table) Not able to set width / styling

### ISSUE THREAD

**Issue by cobraz** [tabetalt/kit#45]
We are probably setting styling with `sx`. This should be moved one up, so we can set it with React Table's styling (see ref below).

ref:
https://react-table-omega.vercel.app/docs/api/useTable#column-options

**Comment by TanyaDolgopolova** [comment]
@cobraz could you please clarify, we need ability to set width of column by passing the argument to the Table component and set up it by width property in react-table library?

**Comment by cobraz** [comment]
Yes, you are correct. :)
