### ISSUE TITLE
Header margin bottom is missing

### ISSUE THREAD

**Issue by cobraz** [tabetalt/kit#46]
Heading component (at least when using H5) does not have any padding/margin bottom. It should probably?

**Comment by TanyaDolgopolova** [comment]
@cobraz Hi, could you please describe more detail? May some screenshots?

**Comment by cobraz** [comment]
@AnneMatilde 👆

@TanyaDolgopolova, notice that everywhere that I have used `<Heading/>`; I have not added any padding/margin-bottom while waiting for this. Have you seen the files that @AnneMatilde sent on Slack?

**Comment by AnneMatilde** [comment]
@TanyaDolgopolova Hi! I Have now updated the designsystem-file with margins:
![Skjermbilde 2020-10-11 kl  18 29 11](https://user-images.githubusercontent.com/54155334/95684151-d09d6f80-0bef-11eb-9f49-5ba891919c54.png)

Here is the file: https://xd.adobe.com/view/a477efab-1e65-485f-beac-242e58c374a7-f124/

**Comment by TanyaDolgopolova** [comment]
> @TanyaDolgopolova Hi! I Have now updated the designsystem-file with margins:
> ![Skjermbilde 2020-10-11 kl 18 29 11](https://user-images.githubusercontent.com/54155334/95684151-d09d6f80-0bef-11eb-9f49-5ba891919c54.png)
> 
> Here is the file: https://xd.adobe.com/view/a477efab-1e65-485f-beac-242e58c374a7-f124/

Okay, thank you I will check it

**Comment by cobraz** [comment]
Great work, @AnneMatilde 🎉
