### ISSUE TITLE
`sx` not working on Table

### ISSUE THREAD

**Issue by cobraz** [tabetalt/kit#47]
The `sx` prop does not work on `<Table/>`

**Comment by TanyaDolgopolova** [comment]
@cobraz Hi, I have checked sx style on the Table component. There are styling for general table, thead, column and row in this component, it seems that sx property work properly. Could you please describe what exactly are not working on the Table?

**Comment by cobraz** [comment]
I don't remember anymore what this issue is about. I'll close it for now, and we'll reopen it we hit any problems 🙂
