### ISSUE TITLE
Create simple WYSIWYG editor

### ISSUE THREAD

**Issue by cobraz** [tabetalt/kit#51]
<img width="459" alt="Skjermbilde 2020-09-20 kl  15 24 47" src="https://user-images.githubusercontent.com/3726815/93712316-6eec6700-fb55-11ea-8455-347f8f37e316.png">

Ref:
- https://github.com/ianstormtaylor/slate

**Comment by TanyaDolgopolova** [comment]
@cobraz Hi, I have a question about button on top right corner (pen). What is his semantic load? Should this icon be added to text editor?

**Comment by cobraz** [comment]
Ahh, I totally forgot to tell you! The pencil on the top right corner is removed; shouldn't be implemented.

**Comment by cobraz** [comment]
Same goes for any other pencil (such as inside input etc) 👍
